// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:memoria_viva_nicaragua/core/config/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Environment.FIREBASE_WEB_API_KEY,
    appId: '1:126169056537:web:87ce1d2652df4408043188',
    messagingSenderId: '126169056537',
    projectId: 'memoriavivanicaragua',
    authDomain: 'memoriavivanicaragua.firebaseapp.com',
    storageBucket: 'memoriavivanicaragua.firebasestorage.app',
    measurementId: 'G-GL485448RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Environment.FIREBASE_ANDROID_API_KEY,
    appId: '1:126169056537:android:6d64ae229cd61770043188',
    messagingSenderId: '126169056537',
    projectId: 'memoriavivanicaragua',
    storageBucket: 'memoriavivanicaragua.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Environment.FIREBASE_IOS_API_KEY,
    appId: '1:126169056537:ios:60d917ef162ab8cf043188',
    messagingSenderId: '126169056537',
    projectId: 'memoriavivanicaragua',
    storageBucket: 'memoriavivanicaragua.firebasestorage.app',
    iosBundleId: 'com.example.memoriaVivaNicaragua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Environment.FIREBASE_IOS_API_KEY,
    appId: '1:126169056537:ios:60d917ef162ab8cf043188',
    messagingSenderId: '126169056537',
    projectId: 'memoriavivanicaragua',
    storageBucket: 'memoriavivanicaragua.firebasestorage.app',
    iosBundleId: 'com.example.memoriaVivaNicaragua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Environment.FIREBASE_WEB_API_KEY,
    appId: '1:126169056537:web:9c8fa82ab2261504043188',
    messagingSenderId: '126169056537',
    projectId: 'memoriavivanicaragua',
    authDomain: 'memoriavivanicaragua.firebaseapp.com',
    storageBucket: 'memoriavivanicaragua.firebasestorage.app',
    measurementId: 'G-QRW4CN6GRW',
  );
}
