/// Departamentos de Nicaragua
enum Departamento {
  boaco('Boaco'),
  carazo('Carazo'),
  chinandega('Chinandega'),
  chontales('Chontales'),
  esteli('Estelí'),
  granada('Granada'),
  jinotega('Jinotega'),
  leon('León'),
  madriz('Madriz'),
  managua('Managua'),
  masaya('Masaya'),
  matagalpa('Matagalpa'),
  nuevaSegovia('Nueva Segovia'),
  raccs('RACCS'), // Región Autónoma de la Costa Caribe Sur
  raccn('RACCN'), // Región Autónoma de la Costa Caribe Norte
  rioSanJuan('Río San Juan'),
  rivas('Rivas');

  final String nombre;
  const Departamento(this.nombre);

  /// Obtiene el departamento desde un string
  static Departamento? fromString(String nombre) {
    try {
      return Departamento.values.firstWhere(
        (d) => d.nombre.toLowerCase() == nombre.toLowerCase(),
      );
    } catch (_) {
      return null;
    }
  }
}

/// Municipios por departamento
const municipiosPorDepartamento = {
  'managua': [
    'Managua',
    'Ciudad Sandino',
    'El Crucero',
    'Mateare',
    'San Francisco Libre',
    'San Rafael del Sur',
    'Ticuantepe',
    'Tipitapa',
    'Villa El Carmen',
  ],
  'león': [
    'León',
    'Achuapa',
    'El Jicaral',
    'El Sauce',
    'La Paz Centro',
    'Larreynaga',
    'Nagarote',
    'Quezalguaque',
    'Santa Rosa del Peñón',
    'Telica',
  ],
  'masaya': [
    'Masaya',
    'Catarina',
    'La Concepción',
    'Masatepe',
    'Nandasmo',
    'Nindirí',
    'Niquinohomo',
    'San Juan de Oriente',
    'Tisma',
  ],
  'granada': [
    'Granada',
    'Diriá',
    'Diriomo',
    'Nandaime',
  ],
  'rivas': [
    'Rivas',
    'Altagracia',
    'Belén',
    'Buenos Aires',
    'Cárdenas',
    'Moyogalpa',
    'Potosí',
    'San Jorge',
    'San Juan del Sur',
    'Tola',
  ],
  'boaco': [
    'Boaco',
    'Camoapa',
    'San José de los Remates',
    'San Lorenzo',
    'Santa Lucía',
    'Teustepe',
  ],
  'carazo': [
    'Diriamba',
    'Dolores',
    'El Rosario',
    'Jinotepe',
    'La Conquista',
    'La Paz de Carazo',
    'San Marcos',
    'Santa Teresa',
  ],
  'chinandega': [
    'Chinandega',
    'Chichigalpa',
    'Cinco Pinos',
    'Corinto',
    'El Realejo',
    'El Viejo',
    'Posoltega',
    'Puerto Morazán',
    'San Francisco del Norte',
    'San Pedro del Norte',
    'Santo Tomás del Norte',
    'Somotillo',
    'Villanueva',
  ],
  'chontales': [
    'Juigalpa',
    'Acoyapa',
    'Comalapa',
    'Cuapa',
    'El Coral',
    'La Libertad',
    'San Pedro de Lóvago',
    'Santo Domingo',
    'Santo Tomás',
    'Villa Sandino',
  ],
  'estelí': [
    'Estelí',
    'Condega',
    'La Trinidad',
    'Pueblo Nuevo',
    'San Juan de Limay',
    'San Nicolás',
  ],
  'jinotega': [
    'Jinotega',
    'El Cuá',
    'La Concordia',
    'San José de Bocay',
    'San Rafael del Norte',
    'Santa María de Pantasma',
    'Wiwilí de Jinotega',
  ],
  'madriz': [
    'Somoto',
    'Las Sabanas',
    'Palacagüina',
    'San José de Cusmapa',
    'San Juan de Río Coco',
    'San Lucas',
    'Telpaneca',
    'Totogalpa',
    'Yalagüina',
  ],
  'matagalpa': [
    'Matagalpa',
    'Ciudad Darío',
    'El Tuma-La Dalia',
    'Esquipulas',
    'Matiguás',
    'Muy Muy',
    'Rancho Grande',
    'Río Blanco',
    'San Dionisio',
    'San Isidro',
    'San Ramón',
    'Sébaco',
    'Terrabona',
  ],
  'nueva segovia': [
    'Ocotal',
    'Ciudad Antigua',
    'Dipilto',
    'El Jícaro',
    'Jalapa',
    'Macuelizo',
    'Mozonte',
    'Murra',
    'Quilalí',
    'San Fernando',
    'Santa María',
    'Wiwilí de Nueva Segovia',
  ],
  'río san juan': [
    'San Carlos',
    'El Almendro',
    'El Castillo',
    'Morrito',
    'San Juan de Nicaragua',
    'San Miguelito',
  ],
  'raccn': [
    'Puerto Cabezas (Bilwi)',
    'Waspam',
    'Prinzapolka',
    'Bonanza',
    'Rosita',
    'Siuna',
    'Mulukukú',
    'Waslala',
  ],
  'raccs': [
    'Bluefields',
    'Corn Island (Islas del Maíz)',
    'Desembocadura de Río Grande',
    'El Rama',
    'El Tortuguero',
    'Kukra Hill',
    'La Cruz de Río Grande',
    'Laguna de Perlas',
    'Muelle de los Bueyes',
    'Nueva Guinea',
    'Paiwas',
  ],
};